/**
 * MAIN SCRIPT: Stock Price Monitor
 * 
 * Instructions:
 * 1. Replace the IDs below with the ones generated by the setup script.
 */

// CONFIGURATION
let CONFIG = {
  symbol_id:       "200", // <-- REPLACE THIS: text:200
  price_id:        "200", // <-- REPLACE THIS: number:200
  last_updated_id: "201"  // <-- REPLACE THIS: text:201
};
let DEFAULT_SYMBOL = "SLYG.DE";
/**
 * Fetches the current stock price and updates the Shelly component.
 */
function updateStockPrice() {
  Shelly.call("Text.GetStatus", { id: CONFIG.symbol_id }, function(status) {   
    let symbol = (status && status.value) ? status.value : DEFAULT_SYMBOL;
    let url = "https://query1.finance.yahoo.com/v8/finance/chart/" + symbol + "?interval=1d&range=1d";
    
    print("Fetching price for:", symbol);

    Shelly.call("HTTP.GET", { 
      url: url, 
      headers: { "User-Agent": "Mozilla/5.0" } 
    }, function(response) {
      
      if (response.code !== 200) {
        print("Error: HTTP", response.code);
        return;
      }

      try {
        let data = JSON.parse(response.body);
        let price = data.chart.result[0].meta.regularMarketPrice;
        
        print("Received Price:", price, "EUR");

        // Update Price
        Shelly.call("Number.Set", { 
          id: CONFIG.price_id, 
          value: price 
        });
        console.log("Updated Price:", "/rpc/Number.Set?id=" + CONFIG.price_id + "&value=" + price);

        Shelly.call("Sys.GetStatus", {}, function(sysStatus) {
           let timeStr = "Just now";
           if (sysStatus && sysStatus.time) {
             timeStr = sysStatus.time; // "HH:MM" format usually
           }
           Shelly.call("Text.Set", {
             id: CONFIG.last_updated_id,
             value: timeStr
           });
        });
        
      } catch(err) {
        print("Error parsing JSON:", err);
      }
    });
  });
}

// Run immediately
updateStockPrice();

// Run every 1 minute (60,000 ms)
Timer.set(60 * 1000, true, updateStockPrice);